version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 0.15
    commands:
      - wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      - unzip terraform_0.15.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve