version: 0.2

phases:
  install:
    # runtime-versions:
    #   terraform: 0.15
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip"
      - "unzip terraform_1.3.7_linux_amd64.zip"
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform apply --auto-approve